spring.config.import=optional:file:.env[.properties]

spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS}

app.upload.dir=${APP_UPLOAD_DIR}
app.gemini.api-key=${APP_GEMINI_API_KEY}
app.gemini.model=${APP_GEMINI_MODEL}
